In [1]:
import numpy as np
from sklearn.datasets import make_regression
from sklearn.datasets import make_classification

from ggml.core import Ignite
from ggml.model_selection import train_test_split as ignite_train_test_split

In [2]:
with Ignite("/home/gridgain/ignite/examples/config/example-ignite.xml") as ignite:
    xy = np.column_stack(make_regression(n_targets=1))
    cache = ignite.create_cache("test-regression", parts=1)
    for i in range(xy.shape[0]):
        cache.put(i, xy[i])
        
    train_cache, test_cache = ignite_train_test_split(cache)
        
    dataset = test_cache.head(5)

dataset

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,0.404451,-0.079416,1.671421,-0.629835,1.052671,-0.346414,-0.013593,-0.270578,0.669466,-0.137824,...,-0.781283,0.781710,1.688450,0.354024,-0.466034,0.216166,-0.658383,0.042345,1.068560,-1.623874
1,-0.115462,-0.430494,0.719696,0.278431,-0.216185,0.304028,0.855870,-0.466531,-1.930550,1.254593,...,0.066411,-1.223505,0.666385,-0.924617,-0.561516,0.367303,-0.387063,-0.366094,0.315226,-199.454200
2,-1.303342,-3.091762,-0.529450,0.460096,0.750671,2.412276,-1.626719,-1.874770,-0.427449,0.677229,...,-0.849895,-0.865421,0.433212,-0.083687,0.186824,-1.588489,-0.814254,0.139871,-1.750267,-260.306385
3,-1.095338,-0.257795,-0.127901,-2.179434,-0.456381,1.485339,0.462737,0.163870,-0.276093,1.701267,...,0.939191,0.881195,-0.814773,-0.233103,0.512344,-0.565978,0.236746,-0.519206,0.178058,-248.693987
4,0.789149,0.780779,-0.170211,0.152034,0.226875,0.229892,0.670501,0.845770,-0.906323,1.482342,...,1.183782,-0.990360,0.672716,1.703655,0.535362,-1.771381,-1.074637,-0.204697,-0.906930,-65.407968

In [3]:
x, y = make_classification()
xy = np.column_stack((x, y))

In [4]:
from ggml.preprocessing import NormalizationTrainer

with Ignite("/home/gridgain/ignite/examples/config/example-ignite.xml") as ignite:
    cache = ignite.create_cache("test-42")
    for i in range(xy.shape[0]):
        cache.put(i, xy[i])
    
    train_cache, test_cache = ignite_train_test_split(cache)
    
    normalizer = NormalizationTrainer().fit_on_cache(train_cache)
    
    dataset_1 = test_cache.head()
    dataset_2 = test_cache.transform(normalizer).head()

In [5]:
dataset_1

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,-1.726493,-0.964857,-0.714935,0.976065,-2.137008,-1.084982,-0.874178,1.946336,-0.132287,1.729640,...,0.756066,-2.675580,0.644507,-1.225522,-1.859302,-0.496989,-0.130004,-0.513507,-2.181897,1.0
1,1.095847,1.686480,-2.263228,1.265509,0.475234,0.513704,1.360379,-0.045029,0.525104,-1.358979,...,1.503260,-1.114275,0.560589,0.059393,0.431956,1.508329,-0.583124,1.465997,1.200474,1.0
2,-1.943217,1.406327,-0.531072,-0.999555,-1.495050,-0.447301,-0.328181,-1.086589,-0.752822,-0.122512,...,-0.553033,0.425065,-1.052896,0.351993,-0.083628,0.134859,-0.400318,1.146953,-1.154511,0.0
3,0.888602,0.433377,-1.124200,1.075977,-0.089129,-0.652263,1.326819,-1.932127,0.974306,0.927657,...,-0.006308,1.324821,-1.516345,-1.925997,-0.131793,1.342916,-0.888151,0.531575,-1.679855,0.0
4,1.535500,-0.019423,1.444613,0.098420,-0.031768,0.447527,0.080985,0.451007,-0.269463,2.426581,...,0.888864,-0.186745,-2.514798,-0.128813,1.931636,0.011799,0.262520,0.388767,0.465075,0.0

In [6]:
dataset_2

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,-0.281058,-0.157071,-0.116385,0.158895,-0.347887,-0.176626,-0.142309,0.316847,-0.021535,0.281571,...,0.123081,-0.435562,0.104920,-0.199504,-0.302678,-0.080906,-0.021164,-0.083594,-0.355194,1.0
1,0.216623,0.333378,-0.447387,0.250162,0.093943,0.101547,0.268915,-0.008901,0.103801,-0.268639,...,0.297159,-0.220266,0.110815,0.011741,0.085388,0.298161,-0.115270,0.289794,0.237306,1.0
2,-0.438296,0.317199,-0.119784,-0.225451,-0.337211,-0.100889,-0.074022,-0.245082,-0.169800,-0.027633,...,-0.124737,0.095874,-0.237482,0.079393,-0.018862,0.030418,-0.090292,0.258697,-0.260402,0.0
3,0.179109,0.087353,-0.226597,0.216877,-0.017965,-0.131472,0.267437,-0.389445,0.196384,0.186981,...,-0.001271,0.267035,-0.305639,-0.388209,-0.026565,0.270682,-0.179018,0.107146,-0.338596,0.0
4,0.313401,-0.003964,0.294850,0.020088,-0.006484,0.091342,0.016529,0.092052,-0.054998,0.495273,...,0.181420,-0.038115,-0.513279,-0.026291,0.394253,0.002408,0.053581,0.079349,0.094923,0.0

In [7]:
from ggml.preprocessing import NormalizationTrainer

with Ignite("/home/gridgain/ignite/examples/config/example-ignite.xml") as ignite:
    cache = ignite.create_cache("test-42")
    for i in range(xy.shape[0]):
        cache.put(i, xy[i])
    
    res = cache[1:10]
    
res[0:2]

array([[-0.63535219, -0.00906258, -1.04486224, -0.18522727,  0.46114302,
         0.99801836,  0.9571525 , -1.20948097, -1.10944438, -0.33996566,
         0.58986441, -1.2877019 ,  0.07441456, -0.97931663,  1.11089872,
         1.91042481,  0.79622026, -1.05769676, -0.75046454,  1.93227852,
         0.        ],
       [ 0.82315753, -0.62651061, -0.58208061, -0.10476683,  0.80715563,
        -0.08442381, -0.04517267, -0.48118942, -0.23179536, -0.12319085,
         0.34271976,  2.27420878, -0.2743177 , -0.55161716,  0.62517064,
         0.16697734,  1.23433755,  0.79484204, -0.6115065 , -0.28614497,
         0.        ]])

In [8]:
from ggml.preprocessing import NormalizationTrainer

with Ignite("/home/gridgain/ignite/examples/config/example-ignite.xml") as ignite:
    cache = ignite.create_cache("test-42")
    for i in range(xy.shape[0]):
        cache.put(i, xy[i])
    
    train_cache, test_cache = ignite_train_test_split(cache)
    
    normalizer = NormalizationTrainer().fit_on_cache(train_cache)
    
    dataset_1 = test_cache.head()
    dataset_2 = test_cache.transform(normalizer).head()